name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Prerelease"
        required: true
        default: false
        type: boolean
      draft:
        description: "Draft"
        required: true
        default: false
        type: boolean
      version-increment-type:
        description: 'Which part of the version to increment:'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: 'patch'

permissions:
  contents: write

jobs:
  release:
    name: Version Bump and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          fetch-depth: 0

      - uses: DevCycleHQ/release-action/prepare-release@main
        id: prepare-release
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: ${{ github.event.inputs.draft }}
          version-increment-type: ${{ github.event.inputs.version-increment-type }}

      - uses: DevCycleHQ/release-action/create-release@main
        id: create-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.prepare-release.outputs.next-release-tag }}
          target: main
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: ${{ github.event.inputs.draft }}
          changelog: ${{ steps.prepare-release.outputs.changelog }}

      - name: Display link to release
        run: |
          echo "::notice title=Release ID::${{ steps.create-release.outputs.release-id }}"
          echo "::notice title=Release URL::${{ steps.create-release.outputs.release-url }}"